server:
    port: 9190
spring:
    cloud:
        gateway:
            routes:
            - id: JWT restricted API
              uri: "http://localhost:9191"
              predicates:
              - Path=/api1/**
              filters:
              - StripPrefix=1
              - AddRequestParameter=foo, bar
              - AddResponseHeader=X-SomeHeader, Bar

spring.jackson.serialization.indent_output: true